apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-automation-demo
  namespace: argowave
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argo
    notifications.argoproj.io/subscribe.on-deployed.slack: argo
    notifications.argoproj.io/subscribe.on-sync-failed.slack: argo
    notifications.argoproj.io/subscribe.on-health-degraded.slack: argo
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: argo
    notifications.argoproj.io/subscribe.on-sync-status-running.slack: argo
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: chart
    repoURL: https://github.com/MatusBalko/demo-cicd-automation-app.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
