apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
data:
  slack-token: eG94Yi03MTY4ODMzNzQxMDQyLTcxODI4Nzk3ODIxMTQtZzIyanJ2b3JXc0dMWHpaN2NOQ0s5SUFx
type: Opaque
